/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProjectIdRouteImport } from './routes/project.$id'
import { Route as ApiArtifactsIdRouteImport } from './routes/api/artifacts.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiSunoCallbackRouteImport } from './routes/api/suno.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdRoute = ProjectIdRouteImport.update({
  id: '/project/$id',
  path: '/project/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArtifactsIdRoute = ApiArtifactsIdRouteImport.update({
  id: '/api/artifacts/$id',
  path: '/api/artifacts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSunoCallbackRoute = ApiSunoCallbackRouteImport.update({
  id: '/api/suno/callback',
  path: '/api/suno/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jobs': typeof JobsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/project/$id': typeof ProjectIdRoute
  '/api/artifacts/$id': typeof ApiArtifactsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/suno/callback': typeof ApiSunoCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jobs': typeof JobsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/project/$id': typeof ProjectIdRoute
  '/api/artifacts/$id': typeof ApiArtifactsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/suno/callback': typeof ApiSunoCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jobs': typeof JobsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/project/$id': typeof ProjectIdRoute
  '/api/artifacts/$id': typeof ApiArtifactsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/suno/callback': typeof ApiSunoCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/jobs'
    | '/library'
    | '/login'
    | '/projects'
    | '/settings'
    | '/project/$id'
    | '/api/artifacts/$id'
    | '/api/auth/$'
    | '/api/suno/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/jobs'
    | '/library'
    | '/login'
    | '/projects'
    | '/settings'
    | '/project/$id'
    | '/api/artifacts/$id'
    | '/api/auth/$'
    | '/api/suno/callback'
  id:
    | '__root__'
    | '/'
    | '/jobs'
    | '/library'
    | '/login'
    | '/projects'
    | '/settings'
    | '/project/$id'
    | '/api/artifacts/$id'
    | '/api/auth/$'
    | '/api/suno/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JobsRoute: typeof JobsRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  ProjectsRoute: typeof ProjectsRoute
  SettingsRoute: typeof SettingsRoute
  ProjectIdRoute: typeof ProjectIdRoute
  ApiArtifactsIdRoute: typeof ApiArtifactsIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiSunoCallbackRoute: typeof ApiSunoCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$id': {
      id: '/project/$id'
      path: '/project/$id'
      fullPath: '/project/$id'
      preLoaderRoute: typeof ProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/artifacts/$id': {
      id: '/api/artifacts/$id'
      path: '/api/artifacts/$id'
      fullPath: '/api/artifacts/$id'
      preLoaderRoute: typeof ApiArtifactsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suno/callback': {
      id: '/api/suno/callback'
      path: '/api/suno/callback'
      fullPath: '/api/suno/callback'
      preLoaderRoute: typeof ApiSunoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JobsRoute: JobsRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  ProjectsRoute: ProjectsRoute,
  SettingsRoute: SettingsRoute,
  ProjectIdRoute: ProjectIdRoute,
  ApiArtifactsIdRoute: ApiArtifactsIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiSunoCallbackRoute: ApiSunoCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
